import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#22C55E', // Green primary color
    primaryContainer: '#D1FAE5',
    secondary: '#059669',
    secondaryContainer: '#A7F3D0',
    tertiary: '#0F766E',
    tertiaryContainer: '#CCFBF1',
    surface: '#FFFFFF',
    surfaceVariant: '#F3F4F6',
    background: '#FAFAFA',
    error: '#EF4444',
    errorContainer: '#FEE2E2',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#064E3B',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#064E3B',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#134E4A',
    onSurface: '#1F2937',
    onSurfaceVariant: '#6B7280',
    onBackground: '#1F2937',
    onError: '#FFFFFF',
    onErrorContainer: '#7F1D1D',
    // Custom colors
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
    // Collector app specific colors
    collectorPrimary: '#22C55E',
    collectorSecondary: '#16A34A',
    collectorAccent: '#84CC16',
  },
  fonts: {
    ...MD3LightTheme.fonts,
    displayLarge: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 57,
      lineHeight: 64,
      letterSpacing: -0.25,
    },
    displayMedium: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 45,
      lineHeight: 52,
      letterSpacing: 0,
    },
    displaySmall: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 36,
      lineHeight: 44,
      letterSpacing: 0,
    },
    headlineLarge: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 32,
      lineHeight: 40,
      letterSpacing: 0,
    },
    headlineMedium: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 28,
      lineHeight: 36,
      letterSpacing: 0,
    },
    headlineSmall: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 24,
      lineHeight: 32,
      letterSpacing: 0,
    },
    titleLarge: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 22,
      lineHeight: 28,
      letterSpacing: 0,
    },
    titleMedium: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.15,
    },
    titleSmall: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    bodyLarge: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 16,
      lineHeight: 24,
      letterSpacing: 0.5,
    },
    bodyMedium: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.25,
    },
    bodySmall: {
      fontFamily: 'System',
      fontWeight: '400',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.4,
    },
    labelLarge: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 14,
      lineHeight: 20,
      letterSpacing: 0.1,
    },
    labelMedium: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 12,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
    labelSmall: {
      fontFamily: 'System',
      fontWeight: '600',
      fontSize: 11,
      lineHeight: 16,
      letterSpacing: 0.5,
    },
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  borderRadius: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  elevation: {
    level0: 0,
    level1: 1,
    level2: 3,
    level3: 6,
    level4: 8,
    level5: 12,
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#22C55E',
    primaryContainer: '#064E3B',
    secondary: '#34D399',
    secondaryContainer: '#065F46',
    tertiary: '#14B8A6',
    tertiaryContainer: '#134E4A',
    surface: '#1F2937',
    surfaceVariant: '#374151',
    background: '#111827',
    error: '#EF4444',
    errorContainer: '#7F1D1D',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#A7F3D0',
    onSecondary: '#FFFFFF',
    onSecondaryContainer: '#A7F3D0',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#CCFBF1',
    onSurface: '#F9FAFB',
    onSurfaceVariant: '#D1D5DB',
    onBackground: '#F9FAFB',
    onError: '#FFFFFF',
    onErrorContainer: '#FEE2E2',
    // Custom colors
    success: '#10B981',
    warning: '#F59E0B',
    info: '#3B82F6',
    // Collector app specific colors
    collectorPrimary: '#22C55E',
    collectorSecondary: '#16A34A',
    collectorAccent: '#84CC16',
  },
  ...theme.fonts,
  ...theme.spacing,
  ...theme.borderRadius,
  ...theme.elevation,
};

export type Theme = typeof theme;