import { useState, useCallback, useMemo, lazy, Suspense } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiRequest } from '@/lib/queryClient';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { batchPointInPolygons, polygonsOverlap, polygonAreaSqMeters, pointInPolygon, formatArea, formatDistance, polylineDistance, generateAllBoundaries, generateBoundary } from '@/utils/geo';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { cn } from '@/lib/utils';
import { ArrowLeft, MapPin, Pencil, Trash2, Save, Plus, AlertTriangle, Check, X, Route, ChevronRight, BrainCircuit, Brain, Download } from 'lucide-react';
import { generateKML, downloadKmlFile } from '@/lib/exportKml';

const BoundaryMapView = lazy(() => import('./BoundaryMapView'));

type Screen = 'home' | 'draw-village' | 'draw-ward' | 'draw-ward-preview' | 'edit-roads' | 'mismatches';

interface Boundary { id: number; villageId: string; type: string; wardName: string | null; coordinates: [number, number][]; areaSqMeters: number | null; }
interface Household { id: number; uid: string; headName: string; ward: string | null; latitude: string | null; longitude: string | null; }
interface Road { id: number; name: string; coordinates: [number, number][]; distanceMeters: number; }
interface Mismatch { household: Household; assignedWard: string; locatedInWard: string; }

export default function BoundariesEditor() {
  const { toast } = useToast();
  const { user } = useAuth();
  const qc = useQueryClient();
  const [screen, setScreen] = useState<Screen>('home');
  const [editingWard, setEditingWard] = useState<string | null>(null);
  const [drawingPolygon, setDrawingPolygon] = useState<[number, number][]>([]);
  const [selectedRoadId, setSelectedRoadId] = useState<number | null>(null);
  const [editRoadName, setEditRoadName] = useState('');
  const [deleteTarget, setDeleteTarget] = useState<{ type: 'boundary' | 'road'; id: number; label: string } | null>(null);
  const [dismissedMismatches, setDismissedMismatches] = useState<Set<number>>(new Set());
  const [editingRoadCoords, setEditingRoadCoords] = useState<[number, number][] | null>(null);
  const [showAutoGenerateDialog, setShowAutoGenerateDialog] = useState(false);
  // Households inside the current drawn boundary that belong to other wards
  const [previewInBoundaryMismatches, setPreviewInBoundaryMismatches] = useState<Household[]>([]);
  // Conflict save dialog: 'mismatch' = households in wrong ward inside boundary
  const [saveMismatchDialog, setSaveMismatchDialog] = useState<Household[] | null>(null);
  // Confirm-correct dialog (irreversible)
  const [confirmCorrectHouseholds, setConfirmCorrectHouseholds] = useState<Household[] | null>(null);

  // ─── Queries ──────────────────────────────────────
  const { data: boundaries = [] } = useQuery<Boundary[]>({
    queryKey: ['/api/village-boundaries'],
    queryFn: async () => { const r = await apiRequest('GET', '/api/village-boundaries'); return r.json(); },
  });
  const { data: roads = [] } = useQuery<Road[]>({
    queryKey: ['/api/village-roads'],
    queryFn: async () => { const r = await apiRequest('GET', '/api/village-roads'); return r.json(); },
  });
  const { data: villageInfo } = useQuery<{ wards: string[] }>({
    queryKey: ['/api/villages', user?.villageId],
    enabled: !!user?.villageId,
    queryFn: async () => { const r = await fetch(`/api/villages/${user!.villageId}`, { credentials: 'include' }); return r.json(); },
  });
  const wards = useMemo(() => villageInfo?.wards || [], [villageInfo]);
  const { data: households = [] } = useQuery<Household[]>({
    queryKey: ['/api/households'],
    queryFn: async () => { const r = await apiRequest('GET', '/api/households'); return r.json(); },
  });

  const villageBoundary = useMemo(() => boundaries.find(b => b.type === 'village'), [boundaries]);
  const wardBoundaries = useMemo(() => boundaries.filter(b => b.type === 'ward'), [boundaries]);
  const wardObjects = useMemo(() => wards.map((w, i) => ({ id: i, name: w })), [wards]);

  // Focus points for draw screens — all valid household coords
  const allHouseholdPoints = useMemo<[number, number][]>(() => {
    const pts: [number, number][] = [];
    for (const h of households) {
      if (!h.latitude || !h.longitude) continue;
      const lat = parseFloat(h.latitude); const lng = parseFloat(h.longitude);
      if (!isNaN(lat) && !isNaN(lng)) pts.push([lat, lng]);
    }
    return pts;
  }, [households]);

  // Per-ward focus: only households in the editing ward
  const wardFocusPoints = useMemo<[number, number][]>(() => {
    if (!editingWard) return allHouseholdPoints;
    const pts: [number, number][] = [];
    for (const h of households) {
      if (h.ward !== editingWard || !h.latitude || !h.longitude) continue;
      const lat = parseFloat(h.latitude); const lng = parseFloat(h.longitude);
      if (!isNaN(lat) && !isNaN(lng)) pts.push([lat, lng]);
    }
    return pts.length > 0 ? pts : allHouseholdPoints;
  }, [households, editingWard, allHouseholdPoints]);

  // Road focus: all road coordinate points
  const roadFocusPoints = useMemo<[number, number][]>(() => {
    const pts: [number, number][] = [];
    for (const r of roads) pts.push(...r.coordinates);
    return pts.length > 0 ? pts : allHouseholdPoints;
  }, [roads, allHouseholdPoints]);

  // ─── Mismatch Detection (#23: use batchPointInPolygons) ─────
  const mismatches = useMemo<Mismatch[]>(() => {
    if (wardBoundaries.length === 0) return [];
    const validHouseholds = households.filter(h => h.latitude && h.longitude && h.ward);
    const points: [number, number][] = validHouseholds.map(h => [parseFloat(h.latitude!), parseFloat(h.longitude!)]);
    // Map ward names to numeric IDs for batchPointInPolygons
    const wardNameToIdx = new Map(wards.map((w, i) => [w, i]));
    const polygons = wardBoundaries.filter(b => b.wardName).map(b => ({
      id: wardNameToIdx.get(b.wardName!) ?? -1, coordinates: b.coordinates,
    })).filter(p => p.id >= 0);
    const mapping = batchPointInPolygons(points, polygons);
    const result: Mismatch[] = [];
    for (let i = 0; i < validHouseholds.length; i++) {
      const h = validHouseholds[i];
      const foundIdx = mapping.get(i);
      if (foundIdx !== undefined) {
        const foundWard = wards[foundIdx];
        if (foundWard && foundWard !== h.ward && !dismissedMismatches.has(h.id)) {
          result.push({ household: h, assignedWard: h.ward!, locatedInWard: foundWard });
        }
      }
    }
    return result;
  }, [households, wardBoundaries, wards, dismissedMismatches]);

  const mismatchedIds = useMemo(() => new Set(mismatches.map(m => m.household.id)), [mismatches]);

  // ─── Mutations ────────────────────────────────────
  const saveBoundary = useMutation({
    mutationFn: async (data: { type: string; wardName?: string | null; coordinates: [number, number][] }) => {
      const r = await apiRequest('POST', '/api/village-boundaries', data);
      return r.json();
    },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['/api/village-boundaries'] }); toast({ title: '✅ Boundary saved' }); },
  });

  const deleteBoundaryMut = useMutation({
    mutationFn: async (id: number) => { await apiRequest('DELETE', `/api/village-boundaries/${id}`); },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['/api/village-boundaries'] }); setDeleteTarget(null); toast({ title: 'Boundary deleted' }); },
  });

  const updateRoad = useMutation({
    mutationFn: async ({ id, ...data }: { id: number; name?: string; coordinates?: [number, number][]; distanceMeters?: number }) => {
      const r = await apiRequest('PATCH', `/api/village-roads/${id}`, data);
      return r.json();
    },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['/api/village-roads'] }); toast({ title: 'Road updated' }); },
  });

  const deleteRoad = useMutation({
    mutationFn: async (id: number) => { await apiRequest('DELETE', `/api/village-roads/${id}`); },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['/api/village-roads'] }); setDeleteTarget(null); setSelectedRoadId(null); toast({ title: 'Road deleted' }); },
  });

  const reassignWards = useMutation({
    mutationFn: async (assignments: { householdId: number; newWard: string }[]) => {
      const r = await apiRequest('POST', '/api/households/reassign-wards', { assignments });
      return r.json();
    },
    onSuccess: () => { qc.invalidateQueries({ queryKey: ['/api/households'] }); toast({ title: '✅ Wards corrected' }); },
  });

  const autoGenerate = useMutation({
    mutationFn: async () => {
      const polys = generateAllBoundaries(households, wards);

      // Client-side overlap check BEFORE sending anything
      const wardEntries = [...polys.entries()].filter(([n]) => n !== '__village__');
      for (let i = 0; i < wardEntries.length; i++) {
        for (let j = i + 1; j < wardEntries.length; j++) {
          if (polygonsOverlap(wardEntries[i][1], wardEntries[j][1])) {
            throw new Error(
              `Ward boundaries overlap: "${wardEntries[i][0]}" and "${wardEntries[j][0]}". ` +
              `This is likely due to households mapped to wrong wards. ` +
              `Please generate boundaries individually for each ward and review.`
            );
          }
        }
      }

      // No overlaps — delete existing then save sequentially
      const existing = await (await apiRequest('GET', '/api/village-boundaries')).json();
      for (const b of (existing || [])) await apiRequest('DELETE', `/api/village-boundaries/${b.id}`);

      for (const [name, coords] of wardEntries) {
        if (!coords || coords.length < 3) continue;
        await apiRequest('POST', '/api/village-boundaries', { type: 'ward', wardName: name, coordinates: coords });
      }
      const village = polys.get('__village__');
      if (village && village.length >= 3) {
        await apiRequest('POST', '/api/village-boundaries', { type: 'village', wardName: null, coordinates: village });
      }
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['/api/village-boundaries'] });
      toast({ title: '✨ Boundaries Generated' });
      setShowAutoGenerateDialog(false);
    },
    onError: (e: any) => {
      setShowAutoGenerateDialog(false);
      toast({ title: 'Cannot auto-generate', description: String(e.message), variant: 'destructive', duration: 8000 });
    },
  });

  // Generate boundary for a single ward and open preview screen
  const handleGenerateWard = useCallback((wardName: string) => {
    const pts: [number, number][] = [];
    for (const h of households) {
      if (h.ward !== wardName || !h.latitude || !h.longitude) continue;
      const lat = parseFloat(h.latitude); const lng = parseFloat(h.longitude);
      if (!isNaN(lat) && !isNaN(lng)) pts.push([lat, lng]);
    }
    if (pts.length < 1) { toast({ title: 'No mapped households', description: `${wardName} has no GPS coordinates yet.`, variant: 'destructive' }); return; }
    const generated = generateBoundary(pts, 30);
    setEditingWard(wardName);
    setDrawingPolygon(generated);
    // Compute which households are inside boundary but assigned to other wards
    const inside = households.filter(h => {
      if (!h.latitude || !h.longitude) return false;
      const lat = parseFloat(h.latitude); const lng = parseFloat(h.longitude);
      return !isNaN(lat) && !isNaN(lng) && pointInPolygon([lat, lng], generated) && h.ward !== wardName;
    });
    setPreviewInBoundaryMismatches(inside);
    setScreen('draw-ward-preview');
  }, [households, toast]);

  // Recompute mismatches when polygon changes in preview screen
  const recomputePreviewMismatches = useCallback((polygon: [number, number][], wardName: string) => {
    const inside = households.filter(h => {
      if (!h.latitude || !h.longitude) return false;
      const lat = parseFloat(h.latitude); const lng = parseFloat(h.longitude);
      return !isNaN(lat) && !isNaN(lng) && pointInPolygon([lat, lng], polygon) && h.ward !== wardName;
    });
    setPreviewInBoundaryMismatches(inside);
  }, [households]);



  // ─── Drawing Handlers ─────────────────────────────
  const handleMapClick = useCallback((latlng: [number, number]) => {
    setDrawingPolygon(prev => [...prev, latlng]);
  }, []);

  // #7: Drag boundary vertex
  const handleVertexDrag = useCallback((idx: number, newPos: [number, number]) => {
    setDrawingPolygon(prev => { const n = [...prev]; n[idx] = newPos; return n; });
  }, []);

  // #8: Drag road vertex
  const handleRoadVertexDrag = useCallback((roadId: number, vertexIdx: number, newPos: [number, number]) => {
    const road = roads.find(r => r.id === roadId);
    if (!road) return;
    const newCoords = [...road.coordinates];
    newCoords[vertexIdx] = newPos;
    setEditingRoadCoords(newCoords);
    updateRoad.mutate({ id: roadId, coordinates: newCoords, distanceMeters: polylineDistance(newCoords) });
  }, [roads, updateRoad]);

  const handleSavePolygon = useCallback((type: 'village' | 'ward', wardName?: string) => {
    if (drawingPolygon.length < 3) {
      toast({ title: 'Need at least 3 points', variant: 'destructive' }); return;
    }
    if (type === 'ward' && wardName) {
      const otherWards = wardBoundaries.filter(b => b.wardName !== wardName);
      for (const other of otherWards) {
        if (polygonsOverlap(drawingPolygon, other.coordinates)) {
          toast({ title: `Overlaps with ${other.wardName}`, description: 'Ward boundaries cannot overlap.', variant: 'destructive' });
          return;
        }
      }
    }
    saveBoundary.mutate(
      { type, wardName: type === 'ward' ? wardName : null, coordinates: drawingPolygon },
      { onSuccess: () => { setDrawingPolygon([]); setScreen('home'); setEditingWard(null); } }
    );
  }, [drawingPolygon, wardBoundaries, saveBoundary, toast]);

  const handleBack = useCallback(() => {
    setScreen('home'); setDrawingPolygon([]); setEditingWard(null); setSelectedRoadId(null);
  }, []);

  // ═══════════════════════════════════════════════════
  // SCREEN: HOME
  // ═══════════════════════════════════════════════════
  if (screen === 'home') {
    const colors = ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#06B6D4', '#84CC16'];

    const handleExportKml = () => {
      const kml = generateKML({
        villageName: 'GreenPath Village Boundaries',
        boundaries,
        roads,
        households,
        showRoads: true,
        showHouseholds: true,
      });
      downloadKmlFile(kml, `Boundary_Map_Export.kml`);
    };

    return (
      <div className="flex flex-col h-full overflow-y-auto bg-gray-50">

        {/* Map — full width, tall, sticky at top */}
        <div className="h-[74vh] relative flex-shrink-0 sticky top-0 p-2">
          {allHouseholdPoints.length === 0 ? (
            <div className="h-full bg-gray-100 animate-pulse flex items-center justify-center">
              <span className="text-xs text-gray-400">Loading map…</span>
            </div>
          ) : (
            <Suspense fallback={<div className="h-full bg-gray-100 animate-pulse" />}>
              <BoundaryMapView households={households} boundaries={boundaries} roads={roads} wards={wardObjects} mismatchedIds={mismatchedIds} focusPoints={allHouseholdPoints} />
            </Suspense>
          )}
          {/* Stats badge on map */}
          <div className="absolute bottom-2 left-2 z-[501] pointer-events-none flex gap-2">
            <div className="bg-white/90 backdrop-blur-sm rounded-lg px-2.5 py-1.5 text-[8px] font-bold text-gray-700 shadow-sm">
              {wardBoundaries.length}/{wards.length} wards
            </div>
            {villageBoundary && (
              <div className="bg-indigo-600/90 backdrop-blur-sm rounded-lg px-2.5 py-1.5 text-[8px] font-bold text-white shadow-sm">
                Village ✓
              </div>
            )}
            {mismatches.length > 0 && (
              <div className="bg-amber-500/90 backdrop-blur-sm rounded-lg px-2.5 py-1.5 text-[8px] font-bold text-white shadow-sm">
                ⚠️ {mismatches.length} mismatched
              </div>
            )}
          </div>
          <div className="absolute bottom-6 right-4 z-[501] pointer-events-auto">
            <button 
              onClick={handleExportKml} 
              className="bg-white/90 backdrop-blur-sm p-2 rounded-xl shadow-sm border border-gray-100 hover:bg-green-50 text-gray-600 hover:text-green-700 transition-colors"
              title="Export visible map as KML"
            >
              <Download className="h-5 w-5" />
            </button>
          </div>
        </div>

        {/* Scrollable content */}
        <div className="flex-1 px-2 pt-1 pb-8 space-y-4">

          {/* Auto-Generate CTA */}
          {boundaries.length === 0 && households.length > 0 && (
            <div className="bg-purple-50 rounded-xl p-4 border border-purple-100">
              <h3 className="text-sm font-bold text-purple-900 mb-1">Setup Boundaries</h3>
              <p className="text-xs text-purple-700 mb-3">Auto-generate village and ward boundaries based on where households are mapped.</p>
              <Button className="w-full bg-purple-600 hover:bg-purple-700" onClick={() => setShowAutoGenerateDialog(true)}>
                Auto-Generate All
              </Button>
            </div>
          )}

          {/* Mismatch alert */}
          {mismatches.length > 0 && (
            <button className="w-full bg-amber-50 border border-amber-200 rounded-xl p-3 text-left flex items-center justify-between" onClick={() => setScreen('mismatches')}>
              <div className="flex items-center gap-2">
                <AlertTriangle className="h-4 w-4 text-amber-600" />
                <div>
                  <p className="text-sm font-bold text-amber-800">{mismatches.length} households in wrong wards</p>
                  <p className="text-[10px] text-amber-600">Tap to review and auto-correct</p>
                </div>
              </div>
              <ChevronRight className="h-4 w-4 text-amber-400" />
            </button>
          )}

          {/* Village Boundary */}
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-2">Village Boundary</p>
            <div className="bg-white rounded-xl border border-gray-100 p-3">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <div className="w-3 h-3 rounded-full" style={{ backgroundColor: '#6366F1' }} />
                  <div>
                    <p className="text-sm font-bold text-gray-900">{villageBoundary ? '✅ Set' : '⚪ Not set'}</p>
                    {villageBoundary && <p className="text-[10px] text-gray-400">{formatArea(villageBoundary.areaSqMeters || 0)}</p>}
                  </div>
                </div>
                <div className="flex gap-1">
                  {villageBoundary && (
                    <button className="p-2 text-gray-300 hover:text-red-500" onClick={() => setDeleteTarget({ type: 'boundary', id: villageBoundary.id, label: 'Village boundary' })}>
                      <Trash2 className="h-4 w-4" />
                    </button>
                  )}
                  <Button size="sm" variant="outline" className="h-8 text-xs text-purple-600 border-purple-200" onClick={() => {
                    if (allHouseholdPoints.length < 1) { toast({ title: 'No household GPS data' }); return; }
                    setDrawingPolygon(generateBoundary(allHouseholdPoints, 45)); setScreen('draw-village');
                  }}> <Brain className="h-3 w-3 mr-1" /> Auto</Button>
                  <Button size="sm" variant="outline" className="h-8 text-xs" onClick={() => { setDrawingPolygon(villageBoundary?.coordinates || []); setScreen('draw-village'); }}>
                    <Pencil className="h-3 w-3 mr-1" /> {villageBoundary ? 'Edit' : 'Draw'}
                  </Button>
                </div>
              </div>
            </div>
          </div>

          {/* Ward Boundaries */}
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-2">Ward Boundaries</p>
            <div className="bg-white rounded-xl border border-gray-100 overflow-hidden">
              {wards.length === 0 ? (
                <p className="p-4 text-xs text-gray-400 text-center">No wards created yet</p>
              ) : (
                wards.map((wardName, idx) => {
                  const wb = wardBoundaries.find(b => b.wardName === wardName);
                  const hhCount = households.filter(h => h.ward === wardName).length;
                  return (
                    <div key={wardName} className={cn('px-3 py-3', idx < wards.length - 1 && 'border-b border-gray-50')}>
                      <div className="flex items-center justify-between">
                        <div className="flex items-center gap-2 flex-1 min-w-0">
                          <div className="w-3 h-3 rounded-full flex-shrink-0" style={{ backgroundColor: colors[idx % colors.length] }} />
                          <div className="min-w-0">
                            <p className="text-sm font-semibold text-gray-900 truncate">{wardName}</p>
                            <p className="text-[10px] text-gray-400">{hhCount} hh{wb ? ` · ${formatArea(wb.areaSqMeters || 0)}` : ' · no boundary'}</p>
                          </div>
                        </div>
                        <div className="flex items-center gap-1 flex-shrink-0">
                          <span className="text-[10px] font-bold text-gray-400">{wb ? '✅' : '⚪'}</span>
                          {wb && (
                            <button className="p-1.5 text-gray-300 hover:text-red-500" onClick={() => setDeleteTarget({ type: 'boundary', id: wb.id, label: wardName })}>
                              <Trash2 className="h-3.5 w-3.5" />
                            </button>
                          )}
                        </div>
                      </div>
                      <div className="flex items-center justify-between mt-2">
                          <Button size="sm" variant="outline" className="h-7 text-[12px] px-2 text-purple-600" onClick={() => handleGenerateWard(wardName)}><Brain className="h-3 w-3 mr-1" /> Auto Generate</Button>
                          <Button size="sm" variant="outline" className="h-7 text-[12px] px-2 rounded-lg " onClick={() => { setEditingWard(wardName); setDrawingPolygon(wb?.coordinates || []); setScreen('draw-ward'); }}>
                            <Pencil className="h-3 w-3 mr-1" />{wb ? 'Edit' : 'Draw'}
                          </Button>                          
                      </div>
                    </div>
                  );
                })
              )}
            </div>
          </div>

          {/* Roads */}
          <div>
            <p className="text-[10px] font-black uppercase tracking-[0.2em] text-gray-400 mb-2">Roads</p>
            <button className="w-full bg-white rounded-xl border border-gray-100 p-3 text-left flex items-center justify-between" onClick={() => setScreen('edit-roads')}>
              <div className="flex items-center gap-2">
                <Route className="h-4 w-4 text-gray-400" />
                <div>
                  <p className="text-sm font-semibold text-gray-900">{roads.length} road{roads.length !== 1 ? 's' : ''}</p>
                  <p className="text-[10px] text-gray-400">{formatDistance(roads.reduce((s, r) => s + (r.distanceMeters || 0), 0))} total</p>
                </div>
              </div>
              <ChevronRight className="h-4 w-4 text-gray-300" />
            </button>
          </div>
        </div>

        {/* Delete confirm overlay */}
        {!!deleteTarget && (
          <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
            <div className="bg-white rounded-2xl p-5 w-full max-w-sm shadow-2xl">
              <h3 className="text-base font-black mb-2">Delete {deleteTarget.label}?</h3>
              <p className="text-xs text-gray-500 mb-4">This action cannot be undone.</p>
              <div className="flex gap-2">
                <Button variant="outline" className="flex-1" onClick={() => setDeleteTarget(null)}>Cancel</Button>
                <Button variant="destructive" className="flex-1" onClick={() => {
                  if (deleteTarget.type === 'boundary') deleteBoundaryMut.mutate(deleteTarget.id);
                  else deleteRoad.mutate(deleteTarget.id);
                }}>Delete</Button>
              </div>
            </div>
          </div>
        )}

        {/* Auto-Generate overlay */}
        {showAutoGenerateDialog && (
          <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
            <div className="bg-white rounded-2xl w-full max-w-md shadow-2xl overflow-hidden">
              {autoGenerate.isPending ? (
                <div className="p-8 text-center">
                  <div className="w-16 h-16 mx-auto mb-4 relative">
                    <div className="absolute inset-0 rounded-full border-4 border-purple-200" />
                    <div className="absolute inset-0 rounded-full border-4 border-purple-600 border-t-transparent animate-spin" />
                    <span className="absolute inset-0 flex items-center justify-center text-xl">✨</span>
                  </div>
                  <h3 className="text-lg font-black mb-2">Generating Boundaries…</h3>
                  <p className="text-sm text-gray-500 mb-4">Building organic boundaries from household locations</p>
                  <div className="flex flex-col gap-1.5 text-left">
                    {wards.map((w, i) => (
                      <div key={w} className="flex items-center gap-2 text-xs text-gray-500">
                        <div className="w-2 h-2 rounded-full bg-purple-400 animate-pulse" style={{ animationDelay: `${i * 120}ms` }} />
                        {w}
                      </div>
                    ))}
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <div className="w-2 h-2 rounded-full bg-indigo-400 animate-pulse" style={{ animationDelay: `${wards.length * 120}ms` }} />
                      Village boundary
                    </div>
                  </div>
                </div>
              ) : (
                <div className="p-6 text-center">
                  <h3 className="text-lg font-black mb-2">Auto-Generate Boundaries</h3>
                  <p className="text-sm text-gray-500 mb-3">Creates organic boundaries wrapping around your mapped households.</p>
                  <ul className="text-xs text-gray-400 mb-6 text-left space-y-1">
                    <li>✔️ Village outer boundary ({households.length} households)</li>
                    {wards.map(w => <li key={w}>✔️ {w} ({households.filter(h => h.ward === w).length} hh)</li>)}
                    <li className="text-amber-600">⚠️ Existing boundaries will be replaced</li>
                  </ul>
                  <div className="flex gap-3">
                    <Button variant="outline" className="flex-1" onClick={() => setShowAutoGenerateDialog(false)}>Cancel</Button>
                    <Button className="flex-1 bg-purple-600 hover:bg-purple-700" onClick={() => autoGenerate.mutate()}>Generate All</Button>
                  </div>
                </div>
              )}
            </div>
          </div>
        )}
      </div>
    );
  }

  // ═══════════════════════════════════════════════════
  // SCREEN: DRAW-WARD-PREVIEW (Generated boundary — review & save)
  // ═══════════════════════════════════════════════════
  if (screen === 'draw-ward-preview' && editingWard) {
    const handlePreviewVertexDrag = (idx: number, newPos: [number, number]) => {
      setDrawingPolygon(prev => {
        const n = [...prev]; n[idx] = newPos;
        recomputePreviewMismatches(n, editingWard);
        return n;
      });
    };
    const handleSavePreview = () => {
      if (drawingPolygon.length < 3) { toast({ title: 'Need at least 3 points', variant: 'destructive' }); return; }
      const others = wardBoundaries.filter(b => b.wardName !== editingWard);
      for (const other of others) {
        if (polygonsOverlap(drawingPolygon, other.coordinates)) {
          toast({ title: `Overlaps with ${other.wardName}`, description: 'Adjust the boundary to remove the overlap.', variant: 'destructive' }); return;
        }
      }
      if (previewInBoundaryMismatches.length > 0) { setSaveMismatchDialog(previewInBoundaryMismatches); return; }
      saveBoundary.mutate(
        { type: 'ward', wardName: editingWard, coordinates: drawingPolygon },
        { onSuccess: () => { setDrawingPolygon([]); setScreen('home'); setEditingWard(null); setSaveMismatchDialog(null); } }
      );
    };

    return (
      <div className="flex flex-col h-full overflow-y-auto bg-gray-50">
        {/* Sticky header */}
        <div className="sticky top-0 z-[10] flex items-center gap-3 px-4 bg-white border-b shadow-sm">
          <button onClick={handleBack} className="p-1"><ArrowLeft className="h-5 w-5 text-gray-600" /></button>
          <div className="flex-1 min-w-0">
            <span className="text-sm font-bold text-gray-900 block truncate">{editingWard}</span>
            <span className="text-[10px] text-purple-600 font-medium">Generated boundary · review &amp; adjust</span>
          </div>
          <span className="text-[10px] text-gray-400 font-mono">{drawingPolygon.length} pts</span>
        </div>

        {/* Map — tall, sticky under header */}
        <div className="h-[70vh] relative flex-shrink-0 sticky top-[49px] p-2">
          <Suspense fallback={<div className="h-full bg-gray-100 animate-pulse" />}>
            <BoundaryMapView
              households={households} boundaries={boundaries} roads={roads} wards={wardObjects}
              drawingPolygon={drawingPolygon} drawMode="draw"
              onMapClick={p => setDrawingPolygon(prev => { const n = [...prev, p]; recomputePreviewMismatches(n, editingWard!); return n; })}
              onVertexDrag={handlePreviewVertexDrag}
              editingWardId={wards.indexOf(editingWard)} focusPoints={wardFocusPoints}
            />
          </Suspense>
          <div className="absolute top-3 left-3 right-3 z-[501] pointer-events-none">
            <div className="bg-white/90 backdrop-blur-sm rounded-lg px-3 py-2 text-[10px] font-bold text-gray-600 shadow-sm inline-block">
              {drawingPolygon.length < 3 ? `Tap map to add points · ${drawingPolygon.length} pts (need 3+)` : `${drawingPolygon.length} pts · Drag vertices · ${formatArea(polygonAreaSqMeters(drawingPolygon))}`}
            </div>
          </div>
        </div>

        {/* Scrollable content below map */}
        <div className="flex-1 px-4 pt-2 pb-8 space-y-3 bg-gray-50">

          {/* Action buttons */}
          <div className="flex gap-2">
            <Button variant="outline" className="flex-1 h-8 rounded-xl text-xs font-bold" onClick={() => { setDrawingPolygon([]); recomputePreviewMismatches([], editingWard); }}>
              <Trash2 className="h-3.5 w-3.5 mr-1" /> Clear
            </Button>
            {drawingPolygon.length > 0 && (
              <Button variant="outline" className="h-8 rounded-xl text-xs font-bold px-4" onClick={() => {
                const n = drawingPolygon.slice(0, -1);
                setDrawingPolygon(n); recomputePreviewMismatches(n, editingWard);
              }}>Undo</Button>
            )}
            <Button className="flex-1 h-8 rounded-xl text-xs font-bold bg-green-600 hover:bg-green-700"
              disabled={drawingPolygon.length < 3 || saveBoundary.isPending} onClick={handleSavePreview}>
              <Save className="h-3.5 w-3.5 mr-1" /> {saveBoundary.isPending ? 'Saving…' : 'Save'}
            </Button>
          </div>

          {/* Mismatch panel */}
          {previewInBoundaryMismatches.length > 0 ? (
            <div className="bg-amber-50 border border-amber-200 rounded-xl p-4">
              <div className="flex items-start gap-2 mb-3">
                <AlertTriangle className="h-4 w-4 text-amber-600 flex-shrink-0 mt-0.5" />
                <div>
                  <p className="text-sm font-bold text-amber-800">{previewInBoundaryMismatches.length} households in wrong wards</p>
                  <p className="text-[10px] text-amber-600 mt-0.5">These households are inside this boundary but assigned to other wards</p>
                </div>
              </div>
              <div className="space-y-1.5 mb-3 max-h-40 overflow-y-auto">
                {previewInBoundaryMismatches.map(h => (
                  <div key={h.id} className="flex items-center justify-between bg-white rounded-lg px-3 py-1.5 border border-amber-100">
                    <span className="text-xs font-medium text-gray-800 truncate flex-1">{h.headName || h.uid}</span>
                    <span className="text-[10px] text-amber-600 ml-2 flex-shrink-0">→ {h.ward}</span>
                  </div>
                ))}
              </div>
              <Button size="sm" className="w-full h-9 text-xs bg-amber-600 hover:bg-amber-700"
                onClick={() => setConfirmCorrectHouseholds(previewInBoundaryMismatches)}>
                Correct all to "{editingWard}"
              </Button>
            </div>
          ) : drawingPolygon.length >= 3 ? (
            <div className="bg-green-50 border border-green-200 rounded-xl p-3 flex items-center gap-2">
              <Check className="h-4 w-4 text-green-600" />
              <p className="text-xs text-green-700 font-medium">All households in boundary are assigned to {editingWard} ✓</p>
            </div>
          ) : null}

          {/* Info */}
          {drawingPolygon.length >= 3 && (
            <div className="bg-white border border-gray-100 rounded-xl p-3">
              <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-2">Boundary Info</p>
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div><span className="text-gray-400">Area</span><br /><span className="font-bold text-gray-900">{formatArea(polygonAreaSqMeters(drawingPolygon))}</span></div>
                <div><span className="text-gray-400">Vertices</span><br /><span className="font-bold text-gray-900">{drawingPolygon.length} points</span></div>
                <div><span className="text-gray-400">Ward households</span><br /><span className="font-bold text-gray-900">{households.filter(h => h.ward === editingWard).length}</span></div>
                <div><span className="text-gray-400">Mismatched</span><br /><span className={`font-bold ${previewInBoundaryMismatches.length > 0 ? 'text-amber-600' : 'text-green-600'}`}>{previewInBoundaryMismatches.length}</span></div>
              </div>
            </div>
          )}
        </div>

        {/* Confirm correct households overlay */}
        {!!confirmCorrectHouseholds && (
          <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.55)' }}>
            <div className="bg-white rounded-2xl p-5 w-full max-w-sm shadow-2xl">
              <h3 className="text-base font-black text-gray-900 mb-2">Correct Household Wards?</h3>
              <p className="text-xs text-gray-500 mb-1">Reassign <strong>{confirmCorrectHouseholds.length}</strong> households to <strong>{editingWard}</strong>.</p>
              <p className="text-xs text-red-500 font-bold mb-5">⚠️ This cannot be undone.</p>
              <div className="flex gap-2">
                <Button variant="outline" className="flex-1" onClick={() => setConfirmCorrectHouseholds(null)} disabled={reassignWards.isPending}>Cancel</Button>
                <Button className="flex-1 bg-amber-600 hover:bg-amber-700" disabled={reassignWards.isPending}
                  onClick={() => {
                    if (!confirmCorrectHouseholds || !editingWard) return;
                    reassignWards.mutate(
                      confirmCorrectHouseholds.map(h => ({ householdId: h.id, newWard: editingWard })),
                      { onSuccess: () => { setConfirmCorrectHouseholds(null); setPreviewInBoundaryMismatches([]); } }
                    );
                  }}>
                  {reassignWards.isPending ? 'Correcting…' : 'Confirm & Correct'}
                </Button>
              </div>
            </div>
          </div>
        )}

        {/* Save mismatch conflict overlay */}
        {!!saveMismatchDialog && (
          <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.55)' }}>
            <div className="bg-white rounded-2xl p-5 w-full max-w-sm shadow-2xl">
              <h3 className="text-base font-black text-gray-900 mb-2">Households in Wrong Wards</h3>
              <p className="text-xs text-gray-500 mb-5"><strong>{saveMismatchDialog.length}</strong> households inside this boundary are assigned to other wards. Saving now may cause overlaps later.</p>
              <div className="flex flex-col gap-2">
                <Button variant="outline" className="w-full" onClick={() => setSaveMismatchDialog(null)}>✏️ Edit Boundary</Button>
                <Button className="w-full bg-amber-600 hover:bg-amber-700"
                  onClick={() => { setSaveMismatchDialog(null); setConfirmCorrectHouseholds(saveMismatchDialog); }}>
                  👥 Correct Households First
                </Button>
                <Button variant="outline" className="w-full text-red-600 border-red-200 hover:bg-red-50"
                  onClick={() => { setSaveMismatchDialog(null); saveBoundary.mutate({ type: 'ward', wardName: editingWard!, coordinates: drawingPolygon }, { onSuccess: () => { setDrawingPolygon([]); setScreen('home'); setEditingWard(null); } }); }}>
                  ⚠️ Save Anyway
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }


  // ═══════════════════════════════════════════════════
  // SCREEN: DRAW VILLAGE / WARD BOUNDARY
  // ═══════════════════════════════════════════════════
  if (screen === 'draw-village' || screen === 'draw-ward') {
    const isVillage = screen === 'draw-village';
    const title = isVillage ? 'Village Boundary' : (editingWard || 'Ward Boundary');
    const focusPoints = isVillage ? allHouseholdPoints : wardFocusPoints;

    return (
      <div className="flex flex-col h-full overflow-y-auto bg-gray-50">
        {/* Sticky header */}
        <div className="sticky top-0 z-[30] flex items-center gap-3 px-4 bg-white border-b shadow-sm">
          <button onClick={handleBack} className="p-1"><ArrowLeft className="h-5 w-5 text-gray-600" /></button>
          <div className="flex-1 min-w-0">
            <span className="text-sm font-bold text-gray-900 block truncate">{title}</span>
            <span className="text-[10px] text-gray-500">{isVillage ? 'Draw outer village boundary' : `Drawing ward boundary`}</span>
          </div>
          <span className="text-[10px] text-gray-400 font-mono">{drawingPolygon.length} pts</span>
        </div>

        {/* Map */}
        <div className="h-[70vh] relative flex-shrink-0 sticky top-[49px] z-[30] p-2">
          <Suspense fallback={<div className="h-full bg-gray-100 animate-pulse" />}>
            <BoundaryMapView
              households={households} boundaries={boundaries} roads={roads} wards={wardObjects}
              drawingPolygon={drawingPolygon} drawMode="draw"
              onMapClick={handleMapClick} onVertexDrag={handleVertexDrag}
              editingWardId={isVillage ? undefined : wards.indexOf(editingWard || '')}
              editingVillage={isVillage} focusPoints={focusPoints}
            />
          </Suspense>
          <div className="absolute bottom-2 left-2 z-[501] pointer-events-none">
            <div className="bg-white/90 backdrop-blur-sm text-[10px] font-bold text-gray-600 shadow-sm inline-block p-1">
              {drawingPolygon.length < 3 ? `Tap map to place points · ${drawingPolygon.length} pts (need 3+)` : `${drawingPolygon.length} pts · Drag to reshape · ${formatArea(polygonAreaSqMeters(drawingPolygon))}`}
            </div>
          </div>
        </div>

        {/* Scrollable content */}
        <div className="flex-1 px-4 pt-1 pb-8 space-y-3 bg-gray-50">
          <div className="flex gap-2">
            <Button variant="outline" className="flex-1 h-8 rounded-xl text-xs font-bold" onClick={() => setDrawingPolygon([])}>
              <Trash2 className="h-3.5 w-3.5 mr-1" /> Clear
            </Button>
            {drawingPolygon.length > 0 && (
              <Button variant="outline" className="h-8 rounded-xl text-xs font-bold px-4" onClick={() => setDrawingPolygon(prev => prev.slice(0, -1))}>Undo</Button>
            )}
            <Button className="flex-1 h-8 rounded-xl text-xs font-bold bg-green-600 hover:bg-green-700"
              disabled={drawingPolygon.length < 3 || saveBoundary.isPending}
              onClick={() => handleSavePolygon(isVillage ? 'village' : 'ward', editingWard ?? undefined)}>
              <Save className="h-3.5 w-3.5 mr-1" /> {saveBoundary.isPending ? 'Saving…' : 'Save'}
            </Button>
          </div>
          {drawingPolygon.length >= 3 && (
            <div className="bg-white border border-gray-100 rounded-xl p-3">
              <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-2">Boundary Info</p>
              <div className="grid grid-cols-2 gap-2 text-xs">
                <div><span className="text-gray-400">Area</span><br /><span className="font-bold">{formatArea(polygonAreaSqMeters(drawingPolygon))}</span></div>
                <div><span className="text-gray-400">Vertices</span><br /><span className="font-bold">{drawingPolygon.length}</span></div>
              </div>
            </div>
          )}
          {drawingPolygon.length === 0 && (
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 text-center">
              <MapPin className="h-6 w-6 text-blue-400 mx-auto mb-2" />
              <p className="text-xs text-blue-600 font-medium">Tap on the map above to place boundary points</p>
              <p className="text-[10px] text-blue-400 mt-1">You can drag vertices after placing them</p>
            </div>
          )}
        </div>
      </div>
    );
  }

  // ═══════════════════════════════════════════════════
  // SCREEN: EDIT ROADS
  // ═══════════════════════════════════════════════════
  if (screen === 'edit-roads') {
    const selectedRoad = roads.find(r => r.id === selectedRoadId);

    return (
      <div className="flex flex-col h-full overflow-y-auto bg-gray-50">
        {/* Sticky header */}
        <div className="sticky top-0 flex items-center gap-3 px-4 bg-white border-b shadow-sm">
          <button onClick={handleBack} className="p-1"><ArrowLeft className="h-5 w-5 text-gray-600" /></button>
          <div className="flex-1">
            <span className="text-sm font-bold text-gray-900">Edit Roads</span>
            <span className="text-[10px] text-gray-800 block">{roads.length} roads · {selectedRoad ? selectedRoad.name : 'tap road to select'}</span>
          </div>
        </div>

        {/* Map */}
        <div className="h-[70vh] relative flex-shrink-0 sticky top-[49px] px-2">
          <Suspense fallback={<div className="h-full bg-gray-100 animate-pulse" />}>
            <BoundaryMapView
              households={households} boundaries={boundaries} roads={roads} wards={wardObjects}
              selectedRoadId={selectedRoadId}
              onRoadSelect={id => { setSelectedRoadId(id); setEditRoadName(roads.find(r => r.id === id)?.name || ''); }}
              onRoadVertexDrag={handleRoadVertexDrag} focusPoints={roadFocusPoints}
            />
          </Suspense>
          {!selectedRoadId && (
            <div className="absolute bottom-0 left-3 z-[501] pointer-events-none">
              <div className="bg-white/90 backdrop-blur-sm px-1 text-[10px] font-bold text-gray-600 shadow-sm inline-block">
                Tap a road on the map to select it
              </div>
            </div>
          )}
        </div>

        {/* Scrollable content */}
        <div className="flex-1 px-2 pt-4 pb-8 space-y-3 bg-gray-50">
          {/* Selected road editor */}
          {selectedRoad ? (
            <div className="bg-white border border-gray-100 rounded-xl p-4">
              <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 mb-3">Selected Road</p>
              <div className="flex items-center gap-2 mb-3">
                <Input value={editRoadName} onChange={e => setEditRoadName(e.target.value)}
                  placeholder="Road name" className="h-10 flex-1 rounded-lg text-sm" maxLength={100} />
                <Button size="sm" className="h-10 px-4 bg-green-600 hover:bg-green-700"
                  disabled={!editRoadName.trim() || updateRoad.isPending}
                  onClick={() => updateRoad.mutate({ id: selectedRoad.id, name: editRoadName.trim() })}>
                  <Save className="h-3.5 w-3.5" />
                </Button>
              </div>
              <div className="flex items-center justify-between text-xs text-gray-400 mb-3">
                <span>{formatDistance(selectedRoad.distanceMeters || 0)} · {selectedRoad.coordinates.length} points</span>
                <span className="text-[10px] text-gray-400">Drag vertices on map to reshape</span>
              </div>
              <div className="flex gap-2">
                <Button variant="outline" className="flex-1 h-9 text-xs" onClick={() => setSelectedRoadId(null)}>Deselect</Button>
                <Button variant="outline" className="flex-1 h-9 text-xs text-red-600 border-red-200 hover:bg-red-50"
                  onClick={() => setDeleteTarget({ type: 'road', id: selectedRoad.id, label: selectedRoad.name })}>
                  <Trash2 className="h-3.5 w-3.5 mr-1" /> Delete
                </Button>
              </div>
            </div>
          ) : (
            <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 text-center">
              <Route className="h-6 w-6 text-blue-400 mx-auto mb-2" />
              <p className="text-xs text-blue-600 font-medium">Tap any road on the map to edit it</p>
            </div>
          )}

          {/* Road list */}
          <div className="bg-white border border-gray-100 rounded-xl overflow-hidden">
            <p className="text-[10px] font-black uppercase tracking-widest text-gray-400 px-4 pt-3 pb-2">All Roads</p>
            {roads.map((road, idx) => (
              <button key={road.id}
                className={cn('w-full flex items-center justify-between px-4 py-2.5 text-left', idx < roads.length - 1 && 'border-b border-gray-50', selectedRoadId === road.id && 'bg-blue-50')}
                onClick={() => { setSelectedRoadId(road.id); setEditRoadName(road.name); }}>
                <div>
                  <p className="text-xs font-semibold text-gray-900">{road.name}</p>
                  <p className="text-[10px] text-gray-400">{formatDistance(road.distanceMeters || 0)} · {road.coordinates.length} pts</p>
                </div>
                <ChevronRight className="h-4 w-4 text-gray-300" />
              </button>
            ))}
          </div>
        </div>

        {/* Delete confirm overlay */}
        {!!deleteTarget && (
          <div className="fixed inset-0 z-[99999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
            <div className="bg-white rounded-2xl p-5 w-full max-w-sm shadow-2xl">
              <h3 className="text-base font-black mb-2">Delete {deleteTarget.label}?</h3>
              <p className="text-xs text-gray-500 mb-4">This action cannot be undone.</p>
              <div className="flex gap-2">
                <Button variant="outline" className="flex-1" onClick={() => setDeleteTarget(null)}>Cancel</Button>
                <Button variant="destructive" className="flex-1" onClick={() => { if (deleteTarget) deleteRoad.mutate(deleteTarget.id); }}>Delete</Button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // ═══════════════════════════════════════════════════
  // SCREEN: MISMATCHES
  // ═══════════════════════════════════════════════════
  if (screen === 'mismatches') {


    return (
      <div className="flex flex-col h-full bg-gray-50">
        <div className="flex items-center gap-3 px-4 py-3 bg-white border-b">
          <button onClick={handleBack} className="p-1"><ArrowLeft className="h-5 w-5 text-gray-600" /></button>
          <span className="text-sm font-bold text-gray-900">Ward Mismatches</span>
        </div>
        <div className="flex-1 overflow-y-auto px-4 mt-3 pb-24">
          <p className="text-xs text-gray-500 mb-3">
            <AlertTriangle className="inline h-3 w-3 text-amber-500 mr-1" />
            {mismatches.length} household{mismatches.length !== 1 ? 's' : ''} located in a different ward than assigned.
          </p>
          {mismatches.map(m => (
            <div key={m.household.id} className="bg-white rounded-xl border border-gray-100 p-3 mb-2">
              <p className="text-sm font-bold text-gray-900">{m.household.headName || m.household.uid}</p>
              <div className="flex items-center gap-2 mt-1 text-[10px]">
                <span className="text-gray-400">Assigned: <strong className="text-gray-600">{m.assignedWard}</strong></span>
                <span className="text-gray-300">→</span>
                <span className="text-amber-600">Located in: <strong>{m.locatedInWard}</strong></span>
              </div>
              <div className="flex gap-2 mt-2">
                <Button size="sm" variant="outline" className="flex-1 h-7 text-[10px]"
                  onClick={() => setDismissedMismatches(prev => { const s = new Set(prev); s.add(m.household.id); return s; })}>
                  <X className="h-3 w-3 mr-1" /> Keep
                </Button>
                <Button size="sm" className="flex-1 h-7 text-[10px] bg-amber-600 hover:bg-amber-700"
                  onClick={() => reassignWards.mutate([{ householdId: m.household.id, newWard: m.locatedInWard }])}>
                  <Check className="h-3 w-3 mr-1" /> → Change
                </Button>
              </div>
            </div>
          ))}
        </div>
        <div className="fixed bottom-0 left-0 right-0 p-3 bg-white border-t z-40" style={{ paddingBottom: 'calc(env(safe-area-inset-bottom) + 12px)' }}>
          <Button
            className="w-full h-11 rounded-xl text-sm font-bold bg-amber-600 hover:bg-amber-700"
            disabled={reassignWards.isPending}
            onClick={() => reassignWards.mutate(
              mismatches.map(m => ({ householdId: m.household.id, newWard: m.locatedInWard })),
              { onSuccess: () => setScreen('home') }
            )}
          >
            <Check className="h-4 w-4 mr-2" /> Auto-Correct All ({mismatches.length})
          </Button>
        </div>
      </div>
    );
  }

}
